# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - name: "Release R github"
    r: release
    env: automlr='github'
    after_success:
      - Rscript -e 'covr::codecov()'

  - name: "Release R github OSX"
    r: release
    env: automlr='github'
    os: osx
